version: '3.4'

services:

  spkl-api:
    image: ${DOCKER_REGISTRY-}spklapi
    build:
      context: .
      dockerfile: SPKL-API/Dockerfile
    depends_on:
      - mssql
  

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
       - "1433:1433"
    restart: always
